# Generated by Django 5.2.8 on 2026-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usuario_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
