# Generated by Django 5.2.8 on 2026-08-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_fecha_nacimiento_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Flag set by admin-assisted password recovery to force the user to set a new password on next login. Reset by the change-password flow once the user picks a new password.'),
        ),
    ]
