# Generated by Django 5.2.8 on 2026-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biometric_external_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Stable opaque identity issued by the pre_save signal. Sent to DP4500 on every service API call.', null=True, unique=True),
        ),
    ]
