# Generated by Django 5.2.8 on 2026-05-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ADMIN_PAYMENT_PENDING_CONFIRMATION', 'Admin Payment Pending Confirmation'), ('ADMIN_MESSAGE_FROM_GENERAL_ADMIN', 'Admin Message From General Admin'), ('ADMIN_MESSAGE_FROM_SPECIALIST', 'Admin Message From Specialist'), ('ADMIN_MESSAGE_FROM_ADMIN', 'Admin Message From Admin'), ('CLIENT_PAYMENT_CONFIRMED', 'Client Payment Confirmed'), ('CLIENT_PAYMENT_REJECTED', 'Client Payment Rejected'), ('CLIENT_PAYMENT_CANCELLED', 'Client Payment Cancelled'), ('CLIENT_PAYMENT_PENDING_REVERSION', 'Client Payment Pending Reversion'), ('CLIENT_APPOINTMENT_CANCELLED', 'Client Appointment Cancelled'), ('CLIENT_APPOINTMENT_RESCHEDULED', 'Client Appointment Rescheduled'), ('SPECIALIST_MESSAGE_FROM_ADMIN', 'Specialist Message From Admin')], max_length=80),
        ),
    ]
