from django.urls import include, path

from config.api.routers_operaciones import citas_d8_router
from config.api.routers_clientes import clientes_router, free_medical_router
from config.api.routers_payments import pagos_router
from config.worker_urls import worker_urlpatterns

from config.admin_availability_views import (
    admin_availability,
    admin_create_habitual_schedule,
    admin_create_specialist_exception,
    admin_delete_habitual_schedule,
    admin_delete_specialist_exception,
    admin_manage_global_day,
    admin_update_habitual_schedule,
    admin_check_concurrency,
    admin_check_maquinaria,
    admin_check_especialistas,
    admin_get_branches,
)
from accounts.views import (
    usuario_recovery_detail,
    usuario_recovery_reset,
    usuario_recovery_search,
)
from config.api_views import (
    admin_actualizar_especialista,
    admin_catalogo_actualizar,
    admin_catalogo_crear,
    admin_catalogo_detalle,
    admin_catalogo_estado,
    admin_maquinaria_actualizar,
    admin_maquinaria_crear,
    admin_cancel_appointment,
    admin_cancel_appointment_verification,
    admin_cliente_create_free_medical_appointment,
    admin_cliente_create_reservation,
    admin_cliente_detalle,
    admin_cliente_free_medical_availability,
    admin_cliente_inactivate,
    admin_cliente_reservation_availability,
    admin_confirm_appointment_biometric,
    admin_mark_appointment_pending_biometric,
    admin_cerrar_cita,
    admin_catalogos,
    admin_grupo_opciones_opciones_list,
    admin_grupo_opciones_opciones_crear,
    admin_grupo_opciones_opciones_crear_multiples,
    admin_grupo_opciones_opciones_actualizar,
    admin_grupo_opciones_opciones_estado,
    admin_crear_especialista,
    admin_crear_prospecto,
    admin_cancel_prospect_medical_appointment,
    admin_create_prospect_medical_appointment,
    admin_dashboard,
    admin_dashboard_payments,
    admin_dashboard_agenda,
    admin_equipo,
    admin_equipo_cambiar_sucursal,
    admin_estado_especialista,
    admin_gasto_actualizar,
    admin_gasto_crear,
    admin_gasto_eliminar,
    admin_gastos,
    admin_gastos_categorias,
    admin_operacion_detalle,
    admin_operaciones,
    admin_pagos,
    admin_prospect_medical_availability,
    admin_prospectos,
    admin_prospecto_migrar,
    admin_update_operation_details,
    admin_update_operation_price_plan,
    admin_delete_operation_quota,
    admin_update_payment_status,
    admin_update_payment_qr_config,
    admin_update_prospect_medical_appointment,
    admin_update_appointment_notes,
    admin_update_appointment_status,
    admin_update_prospect,
    admin_prospect_check_duplicates,
    admin_clientes_global_search,
    admin_set_session_branch,
    admin_reschedule_appointment,
    admin_branch_management_list,
    admin_branch_management_create,
    admin_branch_wizard_initialize,
    admin_branch_wizard_step1,
    admin_branch_wizard_step2,
    admin_branch_wizard_finalize,
    admin_branch_management_update,
    admin_branch_management_toggle,
    admin_branch_management_change_admin,
    admin_branch_management_deactivation_impact,
    admin_branch_admin_audit_logs,
    admin_branch_admins_list,
    admin_branch_admins_create,
    admin_branch_admins_detail,
    admin_branch_admins_update,
    admin_branch_admins_toggle,
    admin_offline_confirmation_conflicts,
    admin_resolve_offline_confirmation_conflict,
    admin_offline_confirmation_metrics,
    admin_report_clients,
    admin_report_prospects,
    admin_report_income,
)
from config.prospect_conversion_views import (
    admin_prospect_conversion_cancel,
    admin_prospect_conversion_detail,
    admin_prospect_conversion_finalize,
    admin_prospect_conversion_biometric_step,
    admin_prospect_conversion_medical_step,
    admin_prospect_conversion_operation_step,
    admin_prospect_conversion_user_step,
    admin_client_reactivation_initialize,
    admin_client_reactivation_detail,
)


urlpatterns = [
    path("trabajador/", include(worker_urlpatterns)),
    path("disponibilidad/sucursales/cambiar/", admin_set_session_branch, name="admin-set-session-branch-api"),
    path("sucursales/", admin_branch_management_list, name="admin-branch-management-list-api"),
    path("sucursales/crear/", admin_branch_management_create, name="admin-branch-management-create-api"),
    path("sucursales/wizard/inicializar/", admin_branch_wizard_initialize, name="admin-branch-wizard-initialize-api"),
    path("sucursales/wizard/paso-1/", admin_branch_wizard_step1, name="admin-branch-wizard-step1-api"),
    path("sucursales/wizard/paso-2/", admin_branch_wizard_step2, name="admin-branch-wizard-step2-api"),
    path("sucursales/wizard/finalizar/", admin_branch_wizard_finalize, name="admin-branch-wizard-finalize-api"),
    path("sucursales/<int:branch_id>/actualizar/", admin_branch_management_update, name="admin-branch-management-update-api"),
    path("sucursales/<int:branch_id>/estado/", admin_branch_management_toggle, name="admin-branch-management-toggle-api"),
    path("sucursales/<int:branch_id>/cambiar-admin/", admin_branch_management_change_admin, name="admin-branch-management-change-admin-api"),
    path("sucursales/<int:branch_id>/deactivation-impact/", admin_branch_management_deactivation_impact, name="admin-branch-management-deactivation-impact-api"),
    path("sucursales/auditoria/", admin_branch_admin_audit_logs, name="admin-branch-admin-audit-logs-api"),
    path("dashboard/", admin_dashboard, name="admin-dashboard-api"),
    path("dashboard/payments/", admin_dashboard_payments, name="admin-dashboard-payments-api"),
    path("dashboard/agenda/", admin_dashboard_agenda, name="admin-dashboard-agenda-api"),
    path("citas/offline/conflictos/", admin_offline_confirmation_conflicts, name="admin-offline-confirmation-conflicts-api"),
    path("citas/offline/conflictos/<slug:event_id>/resolver/", admin_resolve_offline_confirmation_conflict, name="admin-offline-confirmation-conflict-resolve-api"),
    path("citas/offline/metricas/", admin_offline_confirmation_metrics, name="admin-offline-confirmation-metrics-api"),
    path("gastos/", admin_gastos, name="admin-gastos-api"),
    # Admin Reports — branch-scoped, read-only datasets (Phase 1 contract).
    path("reportes/clientes/", admin_report_clients, name="admin-report-clients-api"),
    path("reportes/prospectos/", admin_report_prospects, name="admin-report-prospects-api"),
    path("reportes/ingresos/", admin_report_income, name="admin-report-income-api"),
    # Admin Backups — principal-only dump trigger / list / download / delete.
    path("backups/", include("backups.urls")),
    path("gastos/categorias/", admin_gastos_categorias, name="admin-gastos-categorias-api"),
    path("gastos/crear/", admin_gasto_crear, name="admin-gastos-crear-api"),
    path("gastos/<int:expense_id>/actualizar/", admin_gasto_actualizar, name="admin-gastos-actualizar-api"),
    path("gastos/<int:expense_id>/eliminar/", admin_gasto_eliminar, name="admin-gastos-eliminar-api"),
    path("prospectos/", admin_prospectos, name="admin-prospectos-api"),
    path("prospectos/<int:prospecto_id>/actualizar/", admin_update_prospect, name="admin-prospectos-update-api"),
    path("prospectos/<int:prospecto_id>/migrar/", admin_prospecto_migrar, name="admin-prospectos-migrar-api"),
    path(
        "prospectos/<int:prospecto_id>/cita-medica/disponibilidad/",
        admin_prospect_medical_availability,
        name="admin-prospect-medical-availability-api",
    ),
    path(
        "prospectos/citas/<int:appointment_id>/actualizar/",
        admin_update_prospect_medical_appointment,
        name="admin-prospect-appointment-update-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/cita-medica/reservar/",
        admin_create_prospect_medical_appointment,
        name="admin-prospect-medical-create-api",
    ),
    path(
        "prospectos/citas-medicas/<int:appointment_id>/cancelar/",
        admin_cancel_prospect_medical_appointment,
        name="admin-prospect-medical-cancel-api",
    ),
    path("clientes/buscar-global/", admin_clientes_global_search, name="admin-clientes-global-search-api"),
    path("clientes/<int:client_id>/", admin_cliente_detalle, name="admin-client-detail-api"),
    path(
        "clientes/<int:client_id>/inactivar/",
        admin_cliente_inactivate,
        name="admin-client-inactivate-api",
    ),
    path(
        "clientes/<int:client_id>/operaciones/<int:operation_id>/disponibilidad/",
        admin_cliente_reservation_availability,
        name="admin-client-reservation-availability-api",
    ),
    path(
        "clientes/<int:client_id>/operaciones/<int:operation_id>/reservar/",
        admin_cliente_create_reservation,
        name="admin-client-reservation-create-api",
    ),
    path(
        "clientes/<int:client_id>/cita-medica/disponibilidad/",
        admin_cliente_free_medical_availability,
        name="admin-client-free-medical-availability-api",
    ),
    path(
        "clientes/<int:client_id>/cita-medica/reservar/",
        admin_cliente_create_free_medical_appointment,
        name="admin-client-free-medical-create-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/initialize/",
        admin_client_reactivation_initialize,
        name="admin-client-reactivation-initialize-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/",
        admin_client_reactivation_detail,
        name="admin-client-reactivation-detail-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/cancelar/",
        admin_prospect_conversion_cancel,
        name="admin-client-reactivation-cancel-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/paso-1/",
        admin_prospect_conversion_user_step,
        name="admin-client-reactivation-user-step-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/paso-2/",
        admin_prospect_conversion_operation_step,
        name="admin-client-reactivation-operation-step-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/paso-3/",
        admin_prospect_conversion_medical_step,
        name="admin-client-reactivation-medical-step-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/paso-4/",
        admin_prospect_conversion_biometric_step,
        name="admin-client-reactivation-biometric-step-api",
    ),
    path(
        "clientes/<int:cliente_id>/reactivar/finalizar/",
        admin_prospect_conversion_finalize,
        name="admin-client-reactivation-finalize-api",
    ),
    path("prospectos/verificar-duplicados/", admin_prospect_check_duplicates, name="admin-prospectos-check-duplicates-api"),
    path("prospectos/crear/", admin_crear_prospecto, name="admin-prospectos-create-api"),
    path(
        "prospectos/<int:prospecto_id>/conversion/",
        admin_prospect_conversion_detail,
        name="admin-prospect-conversion-detail-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/cancelar/",
        admin_prospect_conversion_cancel,
        name="admin-prospect-conversion-cancel-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-1/",
        admin_prospect_conversion_user_step,
        name="admin-prospect-conversion-user-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-2/",
        admin_prospect_conversion_operation_step,
        name="admin-prospect-conversion-operation-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-3/",
        admin_prospect_conversion_medical_step,
        name="admin-prospect-conversion-medical-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-4/",
        admin_prospect_conversion_biometric_step,
        name="admin-prospect-conversion-biometric-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/finalizar/",
        admin_prospect_conversion_finalize,
        name="admin-prospect-conversion-finalize-api",
    ),
    path("operaciones/", admin_operaciones, name="admin-operaciones-api"),
    path("operaciones/<int:operacion_id>/", admin_operacion_detalle, name="admin-operacion-detail-api"),
    path(
        "operaciones/<int:operacion_id>/actualizar-detalles/",
        admin_update_operation_details,
        name="admin-operation-update-details-api",
    ),
    path(
        "operaciones/<int:operacion_id>/actualizar-precio/",
        admin_update_operation_price_plan,
        name="admin-operation-update-price-api",
    ),
    path(
        "operaciones/<int:operacion_id>/eliminar-cuota/",
        admin_delete_operation_quota,
        name="admin-operation-delete-quota-api",
    ),
    path("citas/<int:appointment_id>/cancelar/", admin_cancel_appointment, name="admin-appointment-cancel-api"),
    path(
        "citas/<int:appointment_id>/pendiente-biometria/",
        admin_mark_appointment_pending_biometric,
        name="admin-appointment-pending-biometric-api",
    ),
    path(
        "citas/<int:appointment_id>/cerrar/",
        admin_cerrar_cita,
        name="admin-appointment-cerrar-api",
    ),
    path(
        "citas/<int:appointment_id>/notas/",
        admin_update_appointment_notes,
        name="admin-appointment-notes-api",
    ),
    path(
        "citas/<int:appointment_id>/actualizar/",
        admin_update_appointment_status,
        name="admin-appointment-status-update-api",
    ),
    path(
        "citas/<int:appointment_id>/confirmar-biometria/",
        admin_confirm_appointment_biometric,
        name="admin-appointment-biometric-confirm-api",
    ),
    path(
        "citas/<int:appointment_id>/cancelar-verificacion/",
        admin_cancel_appointment_verification,
        name="admin-appointment-cancel-verification-api",
    ),
    path(
        "citas/<int:appointment_id>/reprogramar/",
        admin_reschedule_appointment,
        name="admin-appointment-reschedule-api",
    ),
    path("citas/", include(citas_d8_router.urls)),
    path("disponibilidad/", admin_availability, name="admin-availability-api"),
    path(
        "disponibilidad/habitual/crear/",
        admin_create_habitual_schedule,
        name="admin-availability-habitual-create-api",
    ),
    path(
        "disponibilidad/habitual/<int:rule_id>/actualizar/",
        admin_update_habitual_schedule,
        name="admin-availability-habitual-update-api",
    ),
    path(
        "disponibilidad/habitual/<int:rule_id>/eliminar/",
        admin_delete_habitual_schedule,
        name="admin-availability-habitual-delete-api",
    ),
    path(
        "disponibilidad/excepciones/crear/",
        admin_create_specialist_exception,
        name="admin-availability-exception-create-api",
    ),
    path(
        "disponibilidad/excepciones/<int:exception_id>/eliminar/",
        admin_delete_specialist_exception,
        name="admin-availability-exception-delete-api",
    ),
    path(
        "disponibilidad/global/gestionar/",
        admin_manage_global_day,
        name="admin-availability-global-manage-api",
    ),
    path(
        "disponibilidad/concurrencia/",
        admin_check_concurrency,
        name="admin-availability-check-concurrency-api",
    ),
    path(
        "disponibilidad/check-maquinaria/",
        admin_check_maquinaria,
        name="admin-availability-check-maquinaria-api",
    ),
    path(
        "disponibilidad/check-especialistas/",
        admin_check_especialistas,
        name="admin-availability-check-especialistas-api",
    ),
    path("disponibilidad/sucursales/", admin_get_branches, name="admin-branches-api"),
    path("", include(pagos_router.urls)),
    path("catalogos/", admin_catalogos, name="admin-catalogos-api"),
    # Dedicated Maquinaria endpoints — registered BEFORE the generic
    # catalog patterns so Django's URL resolver routes these specific
    # paths to admin_maquinaria_* (which use @admin_required) instead of
    # matching admin_catalogo_crear/actualizar (which use
    # @_admin_principal_required).
    path(
        "catalogos/maquinaria/crear/",
        admin_maquinaria_crear,
        name="admin-maquinaria-create-api",
    ),
    path(
        "catalogos/maquinaria/<int:item_id>/actualizar/",
        admin_maquinaria_actualizar,
        name="admin-maquinaria-update-api",
    ),
    path("catalogos/<slug:catalog_key>/", admin_catalogo_detalle, name="admin-catalogo-detail-api"),
    path("catalogos/<slug:catalog_key>/crear/", admin_catalogo_crear, name="admin-catalogo-create-api"),
    path(
        "catalogos/<slug:catalog_key>/<int:item_id>/actualizar/",
        admin_catalogo_actualizar,
        name="admin-catalogo-update-api",
    ),
    path(
        "catalogos/<slug:catalog_key>/<int:item_id>/estado/",
        admin_catalogo_estado,
        name="admin-catalogo-state-api",
    ),
    # Nested OpcionCatalogo endpoints under grupos-opciones — used by the
    # option management modal in the admin catalog page. Routes are added
    # next to the generic catalog routes for discoverability.
    path(
        "catalogos/grupos-opciones/<int:grupo_id>/opciones/",
        admin_grupo_opciones_opciones_list,
        name="admin-grupo-opciones-opciones-list-api",
    ),
    path(
        "catalogos/grupos-opciones/<int:grupo_id>/opciones/crear/",
        admin_grupo_opciones_opciones_crear,
        name="admin-grupo-opciones-opciones-crear-api",
    ),
    path(
        "catalogos/grupos-opciones/<int:grupo_id>/opciones/crear-multiples/",
        admin_grupo_opciones_opciones_crear_multiples,
        name="admin-grupo-opciones-opciones-crear-multiples-api",
    ),
    path(
        "catalogos/grupos-opciones/<int:grupo_id>/opciones/<int:opcion_id>/actualizar/",
        admin_grupo_opciones_opciones_actualizar,
        name="admin-grupo-opciones-opciones-actualizar-api",
    ),
    path(
        "catalogos/grupos-opciones/<int:grupo_id>/opciones/<int:opcion_id>/estado/",
        admin_grupo_opciones_opciones_estado,
        name="admin-grupo-opciones-opciones-estado-api",
    ),
    path("equipo/", admin_equipo, name="admin-equipo-api"),
    path("equipo/admins-sucursal/", admin_branch_admins_list, name="admin-branch-admins-list-api"),
    path("equipo/admins-sucursal/crear/", admin_branch_admins_create, name="admin-branch-admins-create-api"),
    path("equipo/admins-sucursal/<int:user_id>/", admin_branch_admins_detail, name="admin-branch-admins-detail-api"),
    path("equipo/admins-sucursal/<int:user_id>/actualizar/", admin_branch_admins_update, name="admin-branch-admins-update-api"),
    path("equipo/admins-sucursal/<int:user_id>/estado/", admin_branch_admins_toggle, name="admin-branch-admins-toggle-api"),
    path("equipo/crear/", admin_crear_especialista, name="admin-equipo-create-api"),
    path(
        "equipo/<int:specialist_id>/actualizar/",
        admin_actualizar_especialista,
        name="admin-equipo-update-api",
    ),
    path(
        "equipo/<int:specialist_id>/estado/",
        admin_estado_especialista,
        name="admin-equipo-status-api",
    ),
    path(
        "equipo/<int:user_id>/cambiar-sucursal/",
        admin_equipo_cambiar_sucursal,
        name="admin-equipo-change-branch-api",
    ),
    path(
        "usuarios/buscar/",
        usuario_recovery_search,
        name="admin-usuarios-buscar-api",
    ),
    path(
        "usuarios/<int:user_id>/",
        usuario_recovery_detail,
        name="admin-usuarios-detail-api",
    ),
    path(
        "usuarios/<int:user_id>/reset-password/",
        usuario_recovery_reset,
        name="admin-usuarios-reset-api",
    ),
    path("", include(free_medical_router.urls)),
    path("", include(clientes_router.urls)),
]
