from django.urls import path

from config.admin_availability_views import (
    admin_availability,
    admin_create_habitual_schedule,
    admin_create_specialist_exception,
    admin_delete_habitual_schedule,
    admin_delete_specialist_exception,
    admin_manage_global_day,
    admin_update_habitual_schedule,
    admin_check_concurrency,
    admin_get_branches,
)
from config.api_views import (
    admin_actualizar_especialista,
    admin_catalogo_actualizar,
    admin_catalogo_crear,
    admin_catalogo_detalle,
    admin_catalogo_estado,
    admin_cancel_appointment,
    admin_cliente_create_reservation,
    admin_cliente_create_free_medical_appointment,
    admin_cliente_detalle,
    admin_cliente_free_medical_availability,
    admin_cliente_inactivate,
    admin_cliente_reservation_availability,
    admin_confirm_appointment_biometric,
    admin_mark_appointment_pending_biometric,
    admin_catalogos,
    admin_crear_especialista,
    admin_crear_prospecto,
    admin_cancel_prospect_medical_appointment,
    admin_create_prospect_medical_appointment,
    admin_dashboard,
    admin_dashboard_payments,
    admin_dashboard_agenda,
    admin_equipo,
    admin_estado_especialista,
    admin_operacion_detalle,
    admin_operaciones,
    admin_pagos,
    admin_prospect_medical_availability,
    admin_prospectos,
    admin_update_operation_details,
    admin_update_operation_price_plan,
    admin_update_payment_status,
    admin_update_payment_qr_config,
    admin_update_prospect,
    admin_update_prospect_medical_appointment,
    admin_update_appointment_status,
)
from config.prospect_conversion_views import (
    admin_prospect_conversion_cancel,
    admin_prospect_conversion_detail,
    admin_prospect_conversion_finalize,
    admin_prospect_conversion_biometric_step,
    admin_prospect_conversion_medical_step,
    admin_prospect_conversion_operation_step,
    admin_prospect_conversion_user_step,
)


urlpatterns = [
    path("dashboard/", admin_dashboard, name="admin-dashboard-api"),
    path("dashboard/payments/", admin_dashboard_payments, name="admin-dashboard-payments-api"),
    path("dashboard/agenda/", admin_dashboard_agenda, name="admin-dashboard-agenda-api"),
    path("prospectos/", admin_prospectos, name="admin-prospectos-api"),
    path("prospectos/<int:prospecto_id>/actualizar/", admin_update_prospect, name="admin-prospectos-update-api"),
    path(
        "prospectos/<int:prospecto_id>/cita-medica/disponibilidad/",
        admin_prospect_medical_availability,
        name="admin-prospect-medical-availability-api",
    ),
    path(
        "prospectos/citas/<int:appointment_id>/actualizar/",
        admin_update_prospect_medical_appointment,
        name="admin-prospect-appointment-update-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/cita-medica/reservar/",
        admin_create_prospect_medical_appointment,
        name="admin-prospect-medical-create-api",
    ),
    path(
        "prospectos/citas-medicas/<int:appointment_id>/cancelar/",
        admin_cancel_prospect_medical_appointment,
        name="admin-prospect-medical-cancel-api",
    ),
    path("clientes/<int:client_id>/", admin_cliente_detalle, name="admin-client-detail-api"),
    path(
        "clientes/<int:client_id>/inactivar/",
        admin_cliente_inactivate,
        name="admin-client-inactivate-api",
    ),
    path(
        "clientes/<int:client_id>/operaciones/<int:operation_id>/disponibilidad/",
        admin_cliente_reservation_availability,
        name="admin-client-reservation-availability-api",
    ),
    path(
        "clientes/<int:client_id>/operaciones/<int:operation_id>/reservar/",
        admin_cliente_create_reservation,
        name="admin-client-reservation-create-api",
    ),
    path(
        "clientes/<int:client_id>/cita-medica/disponibilidad/",
        admin_cliente_free_medical_availability,
        name="admin-client-free-medical-availability-api",
    ),
    path(
        "clientes/<int:client_id>/cita-medica/reservar/",
        admin_cliente_create_free_medical_appointment,
        name="admin-client-free-medical-create-api",
    ),
    path("prospectos/crear/", admin_crear_prospecto, name="admin-prospectos-create-api"),
    path(
        "prospectos/<int:prospecto_id>/conversion/",
        admin_prospect_conversion_detail,
        name="admin-prospect-conversion-detail-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/cancelar/",
        admin_prospect_conversion_cancel,
        name="admin-prospect-conversion-cancel-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-1/",
        admin_prospect_conversion_user_step,
        name="admin-prospect-conversion-user-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-2/",
        admin_prospect_conversion_operation_step,
        name="admin-prospect-conversion-operation-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-3/",
        admin_prospect_conversion_medical_step,
        name="admin-prospect-conversion-medical-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/paso-4/",
        admin_prospect_conversion_biometric_step,
        name="admin-prospect-conversion-biometric-step-api",
    ),
    path(
        "prospectos/<int:prospecto_id>/conversion/finalizar/",
        admin_prospect_conversion_finalize,
        name="admin-prospect-conversion-finalize-api",
    ),
    path("operaciones/", admin_operaciones, name="admin-operaciones-api"),
    path("operaciones/<int:operacion_id>/", admin_operacion_detalle, name="admin-operacion-detail-api"),
    path(
        "operaciones/<int:operacion_id>/actualizar-detalles/",
        admin_update_operation_details,
        name="admin-operation-update-details-api",
    ),
    path(
        "operaciones/<int:operacion_id>/actualizar-precio/",
        admin_update_operation_price_plan,
        name="admin-operation-update-price-api",
    ),
    path("citas/<int:appointment_id>/cancelar/", admin_cancel_appointment, name="admin-appointment-cancel-api"),
    path(
        "citas/<int:appointment_id>/pendiente-biometria/",
        admin_mark_appointment_pending_biometric,
        name="admin-appointment-pending-biometric-api",
    ),
    path(
        "citas/<int:appointment_id>/actualizar/",
        admin_update_appointment_status,
        name="admin-appointment-status-update-api",
    ),
    path(
        "citas/<int:appointment_id>/confirmar-biometria/",
        admin_confirm_appointment_biometric,
        name="admin-appointment-biometric-confirm-api",
    ),
    path("disponibilidad/", admin_availability, name="admin-availability-api"),
    path(
        "disponibilidad/habitual/crear/",
        admin_create_habitual_schedule,
        name="admin-availability-habitual-create-api",
    ),
    path(
        "disponibilidad/habitual/<int:rule_id>/actualizar/",
        admin_update_habitual_schedule,
        name="admin-availability-habitual-update-api",
    ),
    path(
        "disponibilidad/habitual/<int:rule_id>/eliminar/",
        admin_delete_habitual_schedule,
        name="admin-availability-habitual-delete-api",
    ),
    path(
        "disponibilidad/excepciones/crear/",
        admin_create_specialist_exception,
        name="admin-availability-exception-create-api",
    ),
    path(
        "disponibilidad/excepciones/<int:exception_id>/eliminar/",
        admin_delete_specialist_exception,
        name="admin-availability-exception-delete-api",
    ),
    path(
        "disponibilidad/global/gestionar/",
        admin_manage_global_day,
        name="admin-availability-global-manage-api",
    ),
    path(
        "disponibilidad/concurrencia/",
        admin_check_concurrency,
        name="admin-availability-check-concurrency-api",
    ),
    path("disponibilidad/sucursales/", admin_get_branches, name="admin-branches-api"),
    path("pagos/", admin_pagos, name="admin-pagos-api"),
    path("pagos/configuracion-qr/", admin_update_payment_qr_config, name="admin-pagos-qr-config-api"),
    path("pagos/<int:payment_id>/estado/", admin_update_payment_status, name="admin-pagos-status-api"),
    path("catalogos/", admin_catalogos, name="admin-catalogos-api"),
    path("catalogos/<slug:catalog_key>/", admin_catalogo_detalle, name="admin-catalogo-detail-api"),
    path("catalogos/<slug:catalog_key>/crear/", admin_catalogo_crear, name="admin-catalogo-create-api"),
    path(
        "catalogos/<slug:catalog_key>/<int:item_id>/actualizar/",
        admin_catalogo_actualizar,
        name="admin-catalogo-update-api",
    ),
    path(
        "catalogos/<slug:catalog_key>/<int:item_id>/estado/",
        admin_catalogo_estado,
        name="admin-catalogo-state-api",
    ),
    path("equipo/", admin_equipo, name="admin-equipo-api"),
    path("equipo/crear/", admin_crear_especialista, name="admin-equipo-create-api"),
    path(
        "equipo/<int:specialist_id>/actualizar/",
        admin_actualizar_especialista,
        name="admin-equipo-update-api",
    ),
    path(
        "equipo/<int:specialist_id>/estado/",
        admin_estado_especialista,
        name="admin-equipo-status-api",
    ),
]
