# Generated by Django 5.2.8 on 2026-04-18 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisEstetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_analisis', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True)),
                ('grado_deshidratacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_esteticos', to='catalogs.gradodeshidratacion')),
                ('grosor_piel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_esteticos', to='catalogs.grosorpiel')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_esteticos', to='customers.cliente')),
                ('tipo_piel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_esteticos', to='catalogs.tipopiel')),
            ],
            options={
                'db_table': 'analisis_estetico',
                'ordering': ('-fecha_analisis',),
            },
        ),
        migrations.CreateModel(
            name='AnalisisEsteticoAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detalle_reaccion', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='clinical.analisisestetico')),
                ('gravedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_rel', to='catalogs.gravedadalergia')),
                ('producto_alergia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_rel', to='catalogs.productoalergia')),
                ('tipo_alergia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_rel', to='catalogs.tipoalergia')),
            ],
            options={
                'db_table': 'analisis_estetico_alergias',
                'constraints': [models.UniqueConstraint(fields=('analisis', 'producto_alergia', 'tipo_alergia', 'gravedad'), name='uniq_analisis_producto_tipo_gravedad')],
            },
        ),
        migrations.CreateModel(
            name='PatologiaPorAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patologias_rel', to='clinical.analisisestetico')),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analisis_rel', to='catalogs.patologiacutanea')),
            ],
            options={
                'db_table': 'patologias_por_analisis',
                'constraints': [models.UniqueConstraint(fields=('analisis', 'patologia'), name='uniq_patologia_por_analisis')],
            },
        ),
    ]
