# Generated by Django 5.2.8 on 2026-06-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_sector_servicioconfig_sector'),
        ('clinical', '0002_fichacampo_fichaclinica_ficharespuestacampo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaseccion',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_secciones', to='catalogs.sector'),
        ),
        migrations.AlterField(
            model_name='fichaseccion',
            name='proc_estetico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones_ficha', to='catalogs.procestetico'),
        ),
    ]
