# Generated by Django 5.2.8 on 2026-04-18 04:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nro_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_plan_pagos', to='operations.operacion')),
            ],
            options={
                'db_table': 'cuotas_plan_pagos',
                'ordering': ('operacion', 'nro_cuota'),
            },
        ),
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprobante_url', models.CharField(blank=True, max_length=255)),
                ('estado_verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('detalles_pago', models.TextField(blank=True)),
                ('observacion_verificacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='billing.cuotaplanpago')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos_realizados',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cuotaplanpago',
            constraint=models.UniqueConstraint(fields=('operacion', 'nro_cuota'), name='uniq_operacion_nro_cuota'),
        ),
    ]
