# Generated by Django 5.2.8 on 2026-04-25 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrucciones', models.TextField(blank=True, default='Escanea este QR para pagar a la cuenta bancaria de la clinica. Luego adjunta el comprobante para que administracion valide tu pago.')),
                ('imagen_qr', models.FileField(blank=True, null=True, upload_to='pagos_qr/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
            ],
            options={
                'verbose_name': 'Configuracion de pago QR',
                'verbose_name_plural': 'Configuracion de pago QR',
                'db_table': 'configuracion_pago_qr',
            },
        ),
        migrations.AlterField(
            model_name='pagorealizado',
            name='comprobante_url',
            field=models.FileField(blank=True, upload_to='comprobantes_pagos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'pdf'])]),
        ),
    ]
