# Generated by Codex on 2026-05-05

from decimal import Decimal, ROUND_HALF_UP

import django.core.validators
from django.db import migrations, models


def set_initial_quota_amounts(apps, schema_editor):
    CuotaPlanPago = apps.get_model("billing", "CuotaPlanPago")
    for cuota in CuotaPlanPago.objects.select_related("operacion").all():
        operacion = cuota.operacion
        if operacion.cuotas_totales:
            amount = (operacion.precio_total / Decimal(operacion.cuotas_totales)).quantize(
                Decimal("0.01"),
                rounding=ROUND_HALF_UP,
            )
        else:
            amount = operacion.precio_total
        cuota.monto_programado = amount
        cuota.save(update_fields=["monto_programado"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_configuracionpagoqr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuotaplanpago",
            name="monto_programado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(set_initial_quota_amounts, migrations.RunPython.noop),
    ]
