# Generated by Django 5.2.8 on 2026-05-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_categoriagasto_gastosucursal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagorealizado",
            name="estado_verificacion",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
