# Generated by Django 5.2.8 for pagos-fisicos-virtuales (PR 1).

import django.core.validators
from django.db import migrations, models


def backfill_virtual_payments(apps, schema_editor):
    """Idempotent backfill: every existing row becomes a VIRTUAL payment.

    Safe to run twice: the filter only touches rows whose ``metodo_pago`` is
    NULL or empty (i.e. not yet backfilled), so re-running after a partial
    backfill is a no-op for already-migrated rows.

    The backfill assumes every historical row is a virtual payment and
    therefore assigns ``monto_virtual = monto_pagado`` and ``monto_fisico = 0``.
    The existing ``comprobante_url`` requirement keeps these rows valid under
    the new VIRTUAL branch of ``PagoRealizado.clean()``.
    """
    PagoRealizado = apps.get_model("billing", "PagoRealizado")
    PagoRealizado.objects.filter(
        models.Q(metodo_pago__isnull=True) | models.Q(metodo_pago=""),
    ).update(
        metodo_pago="VIRTUAL",
        monto_virtual=models.F("monto_pagado"),
        monto_fisico=0,
    )


def reverse_backfill(apps, schema_editor):
    """Reset the columns added by this migration so reverse migration is clean."""
    PagoRealizado = apps.get_model("billing", "PagoRealizado")
    PagoRealizado.objects.filter(metodo_pago="VIRTUAL").update(
        metodo_pago="",
        monto_virtual=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_migrate_global_qr_to_principal_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorealizado',
            name='metodo_pago',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('FISICO', 'Físico'), ('MIXTO', 'Mixto')], default='VIRTUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='monto_fisico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='monto_virtual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(backfill_virtual_payments, reverse_backfill),
    ]