# Generated by Django 5.2.8 on 2026-04-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('operations', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_cita', to='staff.especialista')),
                ('procedimientos_esteticos', models.ManyToManyField(blank=True, related_name='disponibilidades_cita', to='catalogs.procestetico')),
                ('tipos_proc_estetico', models.ManyToManyField(blank=True, related_name='disponibilidades_cita', to='catalogs.procesteticostipo')),
                ('tipos_servicio', models.ManyToManyField(blank=True, related_name='disponibilidades_cita', to='catalogs.tiposervicio')),
            ],
            options={
                'db_table': 'disponibilidad_citas',
                'ordering': ('fecha_hora', 'especialista__usuario__primer_nombre'),
            },
        ),
        migrations.AddField(
            model_name='citamedica',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_origen', to='operations.disponibilidadcita'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadcita',
            constraint=models.UniqueConstraint(fields=('especialista', 'fecha_hora'), name='uniq_disponibilidad_especialista_fecha_hora'),
        ),
    ]
