# Generated by Django 5.2.8 on 2026-04-23 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_disponibilidadcita_citamedica_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaclinica',
            name='documento_escaneado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichas_clinicas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
