# Generated by Django 5.2.8 on 2026-04-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('operations', '0003_fichaclinica_documento_escaneado_pdf'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBloqueadoAgendaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'agenda_global_dias_bloqueados',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horarios_disponibilidad',
                'ordering': ('hora_inicio', 'hora_fin', 'id'),
                'constraints': [models.UniqueConstraint(fields=('hora_inicio', 'hora_fin'), name='uniq_horario_disponibilidad_rango')],
            },
        ),
        migrations.CreateModel(
            name='AgendaHabitualEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_habituales', to='staff.especialista')),
                ('procedimientos_esteticos', models.ManyToManyField(blank=True, related_name='agendas_habituales', to='catalogs.procestetico')),
                ('tipos_proc_estetico', models.ManyToManyField(blank=True, related_name='agendas_habituales', to='catalogs.procesteticostipo')),
                ('tipos_servicio', models.ManyToManyField(blank=True, related_name='agendas_habituales', to='catalogs.tiposervicio')),
                ('horarios', models.ManyToManyField(blank=True, related_name='agendas_habituales', to='operations.horariodisponibilidad')),
            ],
            options={
                'db_table': 'agendas_habituales_especialista',
                'ordering': ('especialista__usuario__primer_nombre', 'fecha_inicio', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AgendaExcepcionEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo_excepcion', models.CharField(choices=[('AGREGAR', 'Agregar disponibilidad'), ('BLOQUEAR', 'Bloquear disponibilidad')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_agenda', to='staff.especialista')),
                ('procedimientos_esteticos', models.ManyToManyField(blank=True, related_name='excepciones_agenda', to='catalogs.procestetico')),
                ('tipos_proc_estetico', models.ManyToManyField(blank=True, related_name='excepciones_agenda', to='catalogs.procesteticostipo')),
                ('tipos_servicio', models.ManyToManyField(blank=True, related_name='excepciones_agenda', to='catalogs.tiposervicio')),
                ('horarios', models.ManyToManyField(blank=True, related_name='excepciones_agenda', to='operations.horariodisponibilidad')),
            ],
            options={
                'db_table': 'agendas_excepciones_especialista',
                'ordering': ('-fecha', 'especialista__usuario__primer_nombre', 'id'),
            },
        ),
        migrations.AddField(
            model_name='disponibilidadcita',
            name='horario_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_cita', to='operations.horariodisponibilidad'),
        ),
        migrations.CreateModel(
            name='AgendaHabitualDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')])),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='operations.agendahabitualespecialista')),
            ],
            options={
                'db_table': 'agendas_habituales_dias',
                'ordering': ('agenda', 'dia_semana'),
                'constraints': [models.UniqueConstraint(fields=('agenda', 'dia_semana'), name='uniq_agenda_habitual_dia_semana')],
            },
        ),
    ]
