# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
        ("customers", "0003_biometria_mock"),
        ("operations", "0005_citaprospecto"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitaClienteLibre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_hora", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_ASISTIO", "No asistio"),
                        ],
                        default="PROGRAMADA",
                        max_length=32,
                    ),
                ),
                ("detalles_cita", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas_medicas_libres",
                        to="customers.cliente",
                    ),
                ),
                (
                    "disponibilidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas_clientes_libres_origen",
                        to="operations.disponibilidadcita",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_clientes_libres",
                        to="staff.especialista",
                    ),
                ),
                (
                    "servicio_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas_clientes_libres",
                        to="catalogs.servicioconfig",
                    ),
                ),
            ],
            options={
                "db_table": "citas_clientes_libres",
                "ordering": ("fecha_hora",),
            },
        ),
    ]
