# Generated by Django 5.2.8 on 2026-05-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_sucursal'),
        ('customers', '0004_cliente_sucursal_registro_and_more'),
        ('operations', '0006_citaclientelibre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citaprospecto',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='citaclientelibre',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='agendahabitualespecialista',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='agendaexcepcionespecialista',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='citaclientelibre',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='citaprospecto',
            name='medico',
        ),
        migrations.AddField(
            model_name='agendaexcepcionespecialista',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendaexcepcionespecialista',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendaexcepcionespecialista',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_agenda', to='catalogs.sucursal'),
        ),
        migrations.AddField(
            model_name='agendahabitualespecialista',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendahabitualespecialista',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendahabitualespecialista',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_habituales', to='catalogs.sucursal'),
        ),
        migrations.AddField(
            model_name='citaclientelibre',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_clientes_libres', to='catalogs.sucursal'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='catalogs.sucursal'),
        ),
        migrations.AddField(
            model_name='citaprospecto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_prospectos', to='catalogs.sucursal'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='operations.operacion'),
        ),
        migrations.AlterField(
            model_name='citaprospecto',
            name='prospecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='customers.prospecto'),
        ),
        migrations.DeleteModel(
            name='DisponibilidadCita',
        ),
        migrations.DeleteModel(
            name='HorarioDisponibilidad',
        ),
    ]
