# Generated by Django 5.2.8 on 2026-05-06 18:17

from django.db import migrations
from datetime import time


def populate_sucursal_principal(apps, schema_editor):
    Sucursal = apps.get_model('catalogs', 'Sucursal')
    Usuario = apps.get_model('accounts', 'Usuario')
    Cliente = apps.get_model('customers', 'Cliente')
    Prospecto = apps.get_model('customers', 'Prospecto')
    Especialista = apps.get_model('staff', 'Especialista')
    CitaMedica = apps.get_model('operations', 'CitaMedica')
    CitaProspecto = apps.get_model('operations', 'CitaProspecto')
    CitaClienteLibre = apps.get_model('operations', 'CitaClienteLibre')
    AgendaHabitualEspecialista = apps.get_model('operations', 'AgendaHabitualEspecialista')
    AgendaExcepcionEspecialista = apps.get_model('operations', 'AgendaExcepcionEspecialista')

    # Create main branch
    sucursal, _ = Sucursal.objects.get_or_create(
        es_principal=True,
        defaults={
            'nombre': 'Sede Principal',
            'direccion': 'Direccion Central',
            'activa': True
        }
    )

    # Assign to all tables
    Usuario.objects.update(sucursal=sucursal)
    Cliente.objects.update(sucursal_registro=sucursal)
    Prospecto.objects.update(sucursal_registro=sucursal)
    Especialista.objects.update(sucursal_base=sucursal)
    CitaMedica.objects.update(sucursal=sucursal)
    CitaProspecto.objects.update(sucursal=sucursal)
    CitaClienteLibre.objects.update(sucursal=sucursal)

    # For agendas, we must also set dummy hours if they don't have them
    default_start = time(8, 0)
    default_end = time(18, 0)

    AgendaHabitualEspecialista.objects.update(
        sucursal=sucursal,
        hora_inicio=default_start,
        hora_fin=default_end
    )
    
    AgendaExcepcionEspecialista.objects.update(
        sucursal=sucursal,
        hora_inicio=default_start,
        hora_fin=default_end
    )

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_citaprospecto_disponibilidad_and_more'),
        ('accounts', '0002_usuario_sucursal'),
        ('catalogs', '0002_sucursal'),
        ('customers', '0004_cliente_sucursal_registro_and_more'),
        ('staff', '0002_especialista_sucursal_base'),
    ]

    operations = [
        migrations.RunPython(populate_sucursal_principal, reverse_populate)
    ]
