# Generated by Django 5.2.8 on 2026-05-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_sucursal'),
        ('operations', '0008_data_migrate_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaexcepcionespecialista',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_agenda', to='catalogs.sucursal'),
        ),
        migrations.AlterField(
            model_name='agendahabitualespecialista',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_habituales', to='catalogs.sucursal'),
        ),
        migrations.AlterField(
            model_name='citaclientelibre',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_clientes_libres', to='catalogs.sucursal'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='catalogs.sucursal'),
        ),
        migrations.AlterField(
            model_name='citaprospecto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_prospectos', to='catalogs.sucursal'),
        ),
    ]
