# Generated by Django 5.2.8 on 2026-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_agendaexcepcionespecialista_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaprospecto',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], default='PROGRAMADA', max_length=32),
        ),
    ]
