# Generated by Django 5.2.8 on 2026-05-17 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_sucursal_especialistas_pueden_abrir_fichas"),
        ("customers", "0007_prospectoconversionborrador_documento_pdf_and_more"),
        ("operations", "0012_ticketmessage_adjunto"),
    ]

    operations = [
        migrations.AddField(
            model_name="citamedica",
            name="metodo_confirmacion",
            field=models.CharField(
                blank=True,
                choices=[("BIOMETRICO", "Biometrico"), ("TABLET", "Tablet")],
                default="",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="EventoConfirmacionCita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metodo",
                    models.CharField(
                        choices=[("BIOMETRICO", "Biometrico"), ("TABLET", "Tablet")],
                        max_length=16,
                    ),
                ),
                (
                    "confirmado_en",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_confirmacion",
                        to="operations.citamedica",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_confirmacion_citas",
                        to="customers.cliente",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_confirmacion_citas",
                        to="catalogs.sucursal",
                    ),
                ),
            ],
            options={
                "db_table": "eventos_confirmacion_citas",
                "ordering": ("-confirmado_en", "-id"),
            },
        ),
    ]
