# Generated by Django 5.2.8 on 2026-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0014_backfill_citamedica_metodo_confirmacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citamedica",
            name="metodo_confirmacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIOMETRICO", "Biometrico"),
                    ("TABLET", "Tablet"),
                    ("MANUAL", "Manual"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="eventoconfirmacioncita",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("BIOMETRICO", "Biometrico"),
                    ("TABLET", "Tablet"),
                    ("MANUAL", "Manual"),
                ],
                max_length=16,
            ),
        ),
    ]
