# Generated by Django 5.2.8 on 2026-05-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_sucursal_especialistas_pueden_abrir_fichas"),
        ("operations", "0015_alter_citamedica_metodo_confirmacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabletKiosko",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("clave", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kioskos_tablet",
                        to="catalogs.sucursal",
                    ),
                ),
            ],
            options={
                "db_table": "tablet_kioskos",
                "ordering": ("nombre",),
            },
        ),
    ]
