from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_eventoconfirmacioncita_offline_audit_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='fichacampo',
                    name='grupo_opciones',
                ),
                migrations.RemoveField(
                    model_name='fichacampo',
                    name='seccion',
                ),
                migrations.RemoveField(
                    model_name='ficharespuestacampo',
                    name='campo',
                ),
                migrations.RemoveField(
                    model_name='fichacirugiaestetica',
                    name='cirugia',
                ),
                migrations.RemoveField(
                    model_name='fichacirugiaestetica',
                    name='ficha',
                ),
                migrations.RemoveField(
                    model_name='fichaclinica',
                    name='operacion',
                ),
                migrations.RemoveField(
                    model_name='fichaimplanteinjerto',
                    name='ficha',
                ),
                migrations.RemoveField(
                    model_name='ficharespuestacampo',
                    name='ficha',
                ),
                migrations.RemoveField(
                    model_name='fichaimplanteinjerto',
                    name='implante',
                ),
                migrations.RemoveField(
                    model_name='ficharespuestaopcion',
                    name='respuesta',
                ),
                migrations.RemoveField(
                    model_name='ficharespuestaopcion',
                    name='opcion',
                ),
                migrations.RemoveField(
                    model_name='fichaseccion',
                    name='proc_estetico',
                ),
                migrations.RemoveField(
                    model_name='ticket',
                    name='creado_por',
                ),
                migrations.RemoveField(
                    model_name='ticket',
                    name='destinatario_admin',
                ),
                migrations.RemoveField(
                    model_name='ticket',
                    name='especialista',
                ),
                migrations.RemoveField(
                    model_name='ticket',
                    name='sucursal',
                ),
                migrations.RemoveField(
                    model_name='ticketmessage',
                    name='ticket',
                ),
                migrations.RemoveField(
                    model_name='ticketmessage',
                    name='autor',
                ),
                migrations.DeleteModel(
                    name='FichaAntecedenteMedico',
                ),
                migrations.DeleteModel(
                    name='FichaCampo',
                ),
                migrations.DeleteModel(
                    name='FichaCirugiaEstetica',
                ),
                migrations.DeleteModel(
                    name='FichaClinica',
                ),
                migrations.DeleteModel(
                    name='FichaImplanteInjerto',
                ),
                migrations.DeleteModel(
                    name='FichaRespuestaCampo',
                ),
                migrations.DeleteModel(
                    name='FichaRespuestaOpcion',
                ),
                migrations.DeleteModel(
                    name='FichaSeccion',
                ),
                migrations.DeleteModel(
                    name='Ticket',
                ),
                migrations.DeleteModel(
                    name='TicketMessage',
                ),
            ],
            database_operations=[],
        )
    ]
