# Generated by Django 5.2.8 on 2026-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_alter_citamedica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaclientelibre',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistio')], default='PROGRAMADA', max_length=32),
        ),
    ]
