# Generated by Django 5.2.8 on 2026-08-26 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_maquinaria'),
        ('operations', '0025_alter_agendahabitualespecialista_fecha_fin'),
        ('staff', '0003_especialista_puede_abrir_fichas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='descripcion_general',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='duracion_estimada_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duracion estimada en minutos (1..480).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='foto_antes',
            field=models.ImageField(blank=True, null=True, upload_to='citas/%Y/%m/%d/antes/'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='foto_despues',
            field=models.ImageField(blank=True, null=True, upload_to='citas/%Y/%m/%d/despues/'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='hora_real_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='hora_real_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='notas_post',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='notas_previas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='procedimiento_planificado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='procedimiento_realizado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='zona_cuerpo_planificada',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='zona_cuerpo_realizada',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='CitaEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planificada', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas_items', to='operations.citamedica')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_items', to='staff.especialista')),
            ],
            options={
                'db_table': 'citas_especialistas',
                'ordering': ('cita', 'especialista'),
                'constraints': [models.UniqueConstraint(fields=('cita', 'especialista', 'planificada'), name='uniq_cita_especialista_planificada')],
            },
        ),
        migrations.CreateModel(
            name='CitaMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('planificada', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria_items', to='operations.citamedica')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_items', to='catalogs.maquinaria')),
            ],
            options={
                'db_table': 'citas_maquinaria',
                'ordering': ('cita', 'maquinaria'),
                'constraints': [models.UniqueConstraint(fields=('cita', 'maquinaria', 'planificada'), name='uniq_cita_maquinaria_planificada')],
            },
        ),
    ]
