# Generated by Django 5.2.8 on 2026-08-31 23:03

import django.db.models.deletion
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_citamedica_descripcion_general_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('antes', 'Antes'), ('despues', 'Despues')], max_length=10)),
                ('imagen', models.ImageField(upload_to=operations.models._operacion_foto_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_operacion', to='operations.operacion')),
            ],
            options={
                'db_table': 'operaciones_fotos',
                'ordering': ('uploaded_at', 'id'),
                'indexes': [models.Index(fields=['operacion', 'kind', 'uploaded_at', 'id'], name='operaciones_operaci_629554_idx')],
            },
        ),
    ]
