# Generated by Django 5.2.8 on 2026-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_operacion_closure_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='biometric_challenge_id',
            field=models.CharField(blank=True, help_text='DP4500 capture_token returned by the challenge endpoint.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='biometric_match_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Match score from DP4500's verify response (0.0000..9.9999).", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='biometric_verified_at',
            field=models.DateTimeField(blank=True, help_text='Local clock at the moment of the verify response.', null=True),
        ),
    ]
