# Generated by Django 5.2.8 on 2026-07-29 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0006_seed_sectores_and_reassign_fichaseccion'),
        ('customers', '0010_huellabiometricacliente_encrypted_template_key_id_and_more'),
        ('operations', '0024_alter_citaclientelibre_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('public_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_agent_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_agent_tokens', to='catalogs.sucursal')),
            ],
            options={
                'db_table': 'biometric_agent_tokens',
                'ordering': ('sucursal__nombre', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BiometricAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('ENROLL', 'Enrollment'), ('VERIFY', 'Verification')], max_length=16)),
                ('success', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('NO_IMAGE', 'No image'), ('LOW_QUALITY', 'Low capture quality'), ('BELOW_THRESHOLD', 'Score below threshold'), ('DECRYPT_FAILED', 'Decryption failed'), ('AGENT_OFFLINE', 'Agent unreachable')], default='', max_length=32)),
                ('agent_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts_logged', to='biometric.agenttoken')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_attempts', to='operations.citamedica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_attempts', to='customers.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biometric_attempts',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['cita', 'created_at'], name='biometric_atts_cita_created'), models.Index(fields=['cliente', 'operation'], name='biometric_atts_cliente_op')],
            },
        ),
    ]
