# Generated by hand for PR #2: store the Fernet-encrypted raw bearer
# token on the AgentToken row so the backend can perform OUTBOUND
# calls to the agent (e.g. from HttpAgentClient). The agent itself
# never sends the raw token to the backend; the backend retrieves it
# at request time from the encrypted blob.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttoken",
            name="token_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
