# Generated by Django 5.2.8 on 2026-04-18 04:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'antecedentes_medicos',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='CirugiaEstetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'cirugias_esteticas',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='GradoDeshidratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'grados_deshidratacion',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='GravedadAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'gravedades_alergia',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='GrosorPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'grosores_piel',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='GrupoOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grupos_opciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ImplanteInjerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'implantes_injertos',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='PatologiaCutanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'patologias_cutaneas',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='ProcEsteticosTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'proc_esteticos_tipo',
                'ordering': ('orden', 'tipo'),
            },
        ),
        migrations.CreateModel(
            name='ProductoAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'productos_alergia',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='TipoAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'tipos_alergia',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='TipoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'tipos_piel',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'ordering': ('orden', 'tipo'),
            },
        ),
        migrations.CreateModel(
            name='ProcEstetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('proceso', models.CharField(max_length=150)),
                ('tipo_p_estetico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos', to='catalogs.procesteticostipo')),
            ],
            options={
                'db_table': 'proc_esteticos',
                'ordering': ('orden', 'proceso'),
            },
        ),
        migrations.CreateModel(
            name='ServicioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('proc_estetico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_config', to='catalogs.procestetico')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_config', to='catalogs.tiposervicio')),
            ],
            options={
                'db_table': 'servicios_config',
                'ordering': ('tipo_servicio__tipo', 'proc_estetico__proceso'),
            },
        ),
        migrations.CreateModel(
            name='OpcionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogs.grupoopciones')),
            ],
            options={
                'db_table': 'opciones_catalogo',
                'ordering': ('grupo', 'orden', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('grupo', 'codigo'), name='uniq_grupo_codigo_opcion')],
            },
        ),
        migrations.AddConstraint(
            model_name='procestetico',
            constraint=models.UniqueConstraint(fields=('tipo_p_estetico', 'proceso'), name='uniq_tipo_proceso_estetico'),
        ),
        migrations.AddConstraint(
            model_name='servicioconfig',
            constraint=models.UniqueConstraint(fields=('tipo_servicio', 'proc_estetico'), name='uniq_tipo_servicio_proc'),
        ),
    ]
