# Generated by Django 5.2.8 on 2026-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
