# Generated by Django 5.2.8 on 2026-05-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_sucursal_ciudad"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="especialistas_pueden_abrir_fichas",
            field=models.BooleanField(default=True),
        ),
    ]
