# Generated by Django 5.2.8 on 2026-06-25 21:36

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_sucursal_especialistas_pueden_abrir_fichas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'catalogs_sector',
                'ordering': ('orden', 'nombre'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='uniq_sector_codigo_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uniq_sector_nombre_ci')],
            },
        ),
        migrations.AddField(
            model_name='servicioconfig',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_config', to='catalogs.sector'),
        ),
    ]
