# Generated by Django 5.2.8 on 2026-08-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_assign_sector_to_baseline_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquinaria', to='catalogs.sucursal')),
            ],
            options={
                'db_table': 'maquinaria',
                'ordering': ('nombre',),
            },
        ),
    ]
