# Generated by Django 5.2.8 on 2026-09-27 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_maquinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='dp4500_service_key_id',
            field=models.CharField(blank=True, help_text='id of the ServiceAPIKey in DP4500 (cross-project reference).', max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='DP4500 service key id must be 1-64 chars, alphanumeric plus _.- only.', regex='^[A-Za-z0-9_.\\-]{1,64}$')]),
        ),
    ]
