# Generated by Django 5.2.8 on 2026-04-18 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(blank=True, max_length=30)),
                ('estado_cliente', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=20)),
                ('cod_biometrico', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nro_hijos', models.PositiveIntegerField(default=0)),
                ('direccion_domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ocupacion', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ('usuario__primer_nombre', 'usuario__apellido_paterno'),
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('PASAJERO', 'Pasajero'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='PASAJERO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_conversion', models.DateTimeField(blank=True, null=True)),
                ('convertido_a_cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospecto_origen', to='customers.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prospectos',
                'ordering': ('-created_at',),
            },
        ),
    ]
