# Generated by Django 5.2.8 on 2026-04-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectoConversionBorrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paso_actual', models.PositiveSmallIntegerField(choices=[(1, 'Datos de usuario'), (2, 'Operacion'), (3, 'Ficha medica')], default=1)),
                ('paso_usuario_completado', models.BooleanField(default=False)),
                ('paso_operacion_completado', models.BooleanField(default=False)),
                ('paso_ficha_completado', models.BooleanField(default=False)),
                ('datos_usuario', models.JSONField(blank=True, default=dict)),
                ('datos_operacion', models.JSONField(blank=True, default=dict)),
                ('datos_ficha', models.JSONField(blank=True, default=dict)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversiones_prospecto_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrador_conversion', to='customers.prospecto')),
            ],
            options={
                'db_table': 'prospectos_conversion_borrador',
            },
        ),
    ]
