# Generated by Codex on 2026-05-04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_prospectoconversionborrador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prospectoconversionborrador",
            name="datos_biometria",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="prospectoconversionborrador",
            name="paso_biometria_completado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="prospectoconversionborrador",
            name="paso_actual",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Datos de usuario"),
                    (2, "Operacion"),
                    (3, "Ficha medica"),
                    (4, "Biometria"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="HuellaBiometricaCliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proveedor",
                    models.CharField(
                        choices=[("MOCK", "Simulador"), ("SECU_GEN", "SecuGen")],
                        default="MOCK",
                        max_length=20,
                    ),
                ),
                ("template_biometrico", models.TextField()),
                ("device_serial", models.CharField(blank=True, max_length=120)),
                ("calidad_captura", models.PositiveSmallIntegerField(default=0)),
                ("consentimiento_aceptado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huella_biometrica",
                        to="customers.cliente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="huellas_biometricas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clientes_huellas_biometricas",
                "ordering": ("-fecha_registro",),
            },
        ),
    ]
