# Generated by Django 5.2.8 on 2026-05-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_sucursal'),
        ('customers', '0003_biometria_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sucursal_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_registrados', to='catalogs.sucursal'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='sucursal_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_registrados', to='catalogs.sucursal'),
        ),
    ]
