# Generated by Django 5.2.8 on 2026-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cliente_sucursal_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cod_biometrico',
        ),
    ]
