# Generated by Django 5.2.8 on 2026-05-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_cliente_cod_biometrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectoconversionborrador',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrador_reactivacion', to='customers.cliente'),
        ),
        migrations.AlterField(
            model_name='prospectoconversionborrador',
            name='prospecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrador_conversion', to='customers.prospecto'),
        ),
    ]
