# Generated by Django 5.2.8 on 2026-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_prospectoconversionborrador_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectoconversionborrador',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='conversiones/borradores/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
