# Generated by Django 5.2.8 on 2026-05-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_split_prospecto_name_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bloqueo_reactivacion_automatica",
            field=models.BooleanField(default=False),
        ),
    ]
