# Generated by Django 5.2.8 on 2026-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_cliente_bloqueo_reactivacion_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='huellabiometricacliente',
            name='encrypted_template_key_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='huellabiometricacliente',
            name='last_match_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huellabiometricacliente',
            name='last_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='huellabiometricacliente',
            name='template_format',
            field=models.CharField(choices=[('DP_PROPRIETARY', 'DigitalPersona proprietary'), ('ANSI_378', 'ANSI 378'), ('ISO_19794_2', 'ISO 19794-2'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=24),
        ),
        migrations.AlterField(
            model_name='huellabiometricacliente',
            name='proveedor',
            field=models.CharField(choices=[('MOCK_LEGACY', 'Simulador (legacy, inactivo)'), ('SECU_GEN_LEGACY', 'SecuGen (legacy, inactivo)'), ('DIGITAL_PERSONA', 'DigitalPersona 4500')], default='DIGITAL_PERSONA', max_length=24),
        ),
        migrations.AlterField(
            model_name='huellabiometricacliente',
            name='template_biometrico',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
