# Generated by Django 5.2.8 on 2026-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_prospecto_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECURRENTE_PRE_SISTEMA', 'Recurrente pre-sistema')], default='NUEVO', max_length=32),
        ),
    ]
