# Generated by Django 5.2.8 on 2026-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_cliente_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cross-system UUID the DP4500 service API uses to address this cliente. Mirrors Usuario.biometric_external_id once the prospect-conversion finalize handler has wired the wizard-minted UUID.', null=True, unique=True),
        ),
    ]
