# Generated by Django 5.2.8 on 2026-09-27 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCascade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_external_id', models.UUIDField()),
                ('sucursal_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending cascade'), ('completed', 'DP4500 returned 204 or 404'), ('suspended', 'DP4500 returned 503 BIOMETRIC_SUSPENDED; not retryable'), ('failed', 'Exhausted retries')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dp4500_integration_pending_cascade',
                'indexes': [models.Index(fields=['status', 'created_at'], name='dp4500_inte_status_786271_idx'), models.Index(fields=['user_external_id'], name='dp4500_inte_user_ex_6a1191_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiometricEnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_external_id', models.UUIDField()),
                ('wizard_id', models.CharField(max_length=64)),
                ('enrollment_strategy', models.CharField(choices=[('pending', 'Phase 2 stub: capture not yet wired'), ('mock', 'Phase 2 dev: dev-only mock capture'), ('websdk', 'Phase 4: browser Web SDK'), ('electron', 'Phase 4: Electron child process')], default='pending', max_length=16)),
                ('advanced_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('advanced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_advances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrollment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dp4500_integration_enrollment_record',
                'indexes': [models.Index(fields=['user', 'wizard_id'], name='dp4500_inte_user_id_3850de_idx'), models.Index(fields=['enrollment_strategy', 'advanced_at'], name='dp4500_inte_enrollm_c6a315_idx')],
            },
        ),
    ]
