# Generated by Django 5.2.8 on 2026-08-06 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('trigger_download', 'Descarga manual'), ('download_server_backup', 'Descargar respaldo'), ('delete_server_backup', 'Eliminar respaldo'), ('retention_prune', 'Retencion'), ('rate_limit_denied', 'Limite de velocidad'), ('download_denied', 'Descarga rechazada'), ('delete_denied', 'Eliminacion rechazada'), ('trigger_failed', 'Creacion fallida')], max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='backup_audit_created_idx'), models.Index(fields=['action', '-created_at'], name='backup_audit_action_idx')],
            },
        ),
    ]
