# Generated by Django 5.2.8 on 2026-04-18 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'especialidades',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especialista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'especialistas',
                'ordering': ('usuario__primer_nombre', 'usuario__apellido_paterno'),
            },
        ),
        migrations.CreateModel(
            name='EspecialistaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas_rel', to='staff.especialidad')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_rel', to='staff.especialista')),
            ],
            options={
                'db_table': 'especialista_especialidades',
                'constraints': [models.UniqueConstraint(fields=('especialista', 'especialidad'), name='uniq_especialista_especialidad')],
            },
        ),
    ]
