# Generated by Django 5.2.8 on 2026-05-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_sucursal'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='sucursal_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialistas_base', to='catalogs.sucursal'),
        ),
    ]
