# Generated by Django 5.2.8 on 2026-05-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_especialista_sucursal_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialista",
            name="puede_abrir_fichas",
            field=models.BooleanField(default=True),
        ),
    ]
