# Generated by Django 5.2.8 on 2026-10-01 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('SIGNED_URL_ISSUED', 'Signed URL issued'), ('SIGNED_URL_DENIED', 'Signed URL denied')], max_length=32)),
                ('resource_path', models.CharField(max_length=512)),
                ('resource_type', models.CharField(max_length=128)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('denial_reason', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'action', '-created_at'], name='audit_log_user_id_1e05c5_idx'), models.Index(fields=['resource_path', '-created_at'], name='audit_log_resourc_69c26c_idx')],
            },
        ),
    ]
